name: validate
on:
  push:
    branches:
      - quill-mlx
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy --workspace -- -D warnings

  tests:
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [ "1.85.0", stable ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false
          toolchain: ${{ matrix.rust }}
          rustflags: ""
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo test --workspace -- --test-threads=1 # MLX is not thread safe
